### PR TITLE
improve chain config

### PR DESCRIPTION
**Pull request by faddat**
- removes ignite
- removes tests that depend on the ignite cli
- updated sdk.Int to math.Int, used v46 error module correctly
- housekeeping
- might be state breaking, but should not be
- embeds the open api console
- leaves one dependency on cosmoscmd, decision on weather or not to remove that is left as an excercise to the reader

Resolves most of the issues that are found in this document:

https://docs.google.com/document/d/1-K7MRVAcRp2fhw-gONQQ8ommaNPkeVuWGtQdGSrxUTs/edit?usp=sharing

## Urgent note

There are two other issues that I have shared with pfc, the borg, and mr don don cryptonium because I could not reach anyone from Kujira.   They are more serious, so they have been redacted from the findings document above. 

## Summary

So, I did some linting fixes, but the thing to pay attention to here is ignite.  I think that you could use this as a chain upgrade, and I do recommend that you do.  The changes to go.mod are pretty important.

### CODE REVIEW

**Comment by faddat** [comment]
@codehans please make sure to read over getenableed proposals.  Overall this should get the job done.

**Comment by Galadrin** [comment]
Can you explain to us laymen why it is so important to remove Ignite?

**Comment by faddat** [comment]
Hey sure thing @Galadrin -- the Ignite CLI will block properly configuring the chain.  

Previously, it would use a wrapper, cosmoscmd, to start the chain. 

After removing ignite, it can be properly configured.

**Comment by faddat** [comment]
currently a register services issue likely related to proto generation.  Hope to resolve that tomorrow 

this work can be tested like:

```bash
bash statesync.bash
```

**Pull request closed without merging**
